/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dollarbtc.backend.cryptocurrency.exchange.enums;

/**
 *
 * @author CarlosDaniel
 */
public enum BalanceOperationType {

    INITIAL_MOVEMENT,
    SELL,
    BUY,
    SEND,
    SEND_IN,
    SEND_OUT,
    RECEIVE,
    RECEIVE_IN,
    RECEIVE_OUT,
    CURRENCY_CHANGE,
    SEND_TO_PAYMENT,
    MODEL_ACTIVATION,
    MODEL_INACTIVATION,
    MOVE_RESERVE,
    MC_SEND_SMS_NATIONAL,
    MC_SEND_SMS_INTERNATIONAL,
    MC_RETAIL_SELL_BALANCE,
    MC_RETAIL_BUY_BALANCE,
    MC_FAST_CHANGE,
    MC_BUY_BALANCE,
    BROKER_SEND_TO_PAYMENT,
    MC_AUTOMATIC_CHANGE,
    MC_ADD_ESCROW,
    MC_SUBSTRACT_ESCROW,
    MC_MESSAGE_OFFER_CHANGE,
    DEBIT,
    CREDIT,
    FAST_CHANGE,
    TRANSFER_FROM_BALANCE_TO_MCBALANCE,
    TRANSFER_FROM_MCBALANCE_TO_BALANCE,
    TRANSFER_TO_MASTER,
    TRANSFER_BETWEEN_MASTERS,
    MONEY_ORDER_SEND,
    TRANSFER_TO_CLIENTS,
    GIFT_CARD_ACTIVATION,
    GIFT_CARD_BUY,
    GIFT_CARD_REDEEM,
    GIFT_CARD_REDEEM_BR,
    GIFT_CARD_REDEEM_FIAT,
    GIFT_CARD_REDEEM_TC,
    PURCHASE_WITH_DEBIT_CARD,
    BANKER_ADD_BALANCE,
    BANKER_REMOVE_BALANCE,
    BANKER_OPERATION,
    DOLLARBTC_PAYMENT_COMMISSIONS_TO_MONEYCLICK,
    MONEY_CALL_PAY,
    MC_BUY_BITCOINS,
    MC_SELL_BITCOINS,
    MC_BUY_CRYPTO,
    MC_SELL_CRYPTO,
    MC_POST_MESSAGE_OFFER,
    MC_TAKE_MESSAGE_OFFER,
    MC_CASHBACK,
    DEBIT_CARD_REQUEST,
    DEBIT_CARD_ADD_BALANCE,
    DEBIT_CARD_SUBSTRACT_BALANCE,
    MONEY_MARKET_POST_ORDER,
    MONEY_MARKET_TAKE_ORDER,
    MONEY_MARKET_CLOSE_ORDER,
    SUBSCRIPTION_JOIN,
    DONATION,
    CASH_BUY,
    CASH_SELL,
    CASH_SUBSTRACT_ESCROW,
    CASH_ADD_ESCROW;

}
